name: Integrations (Node)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: docker compose run integration_node

      - name: Cleanup
        if: always()
        run: docker compose down
