name: Release httpsnippet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version to release'
        required: true

permissions:
  contents: write

env:
  # Release Tag to build and publish
  TAG: ${{ github.event.inputs.version }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Insomnia Automation app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.GHA_INSOMNIA_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.GHA_INSOMNIA_AUTOMATION_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install
        run: npm ci

      - name: Create new package version
        run: npm version "${{ env.TAG }}"

      - name: DEBUG see tags
        run: |
          git tag --list
          git remote -v

      - name: Push version commit and tags
        run: |
          git push origin v${{ env.TAG }}
          git push origin master

      - name: Create Tag and Release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1
        id: core_tag_and_release
        with:
          tag: v${{ env.TAG }}
          name: 'httpsnippet v${{ env.TAG }} 📦'
          generateReleaseNotes: true
          prerelease: false
          draft: false
          token: ${{ steps.app-token.outputs.token }}
